enable-magisk-update = true
parallel-jobs = 10
compression-level = 9
riplib = true
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations
# you can use rvmm-config-gen to generate a config

[X]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
version = "auto"
arch = "arm64-v8a"

[Gphotos]
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"
arch = "arm64-v8a"

[Spotify]
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
version = "auto"
arch = "arm64-v8a"

[YouTube-Ex]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
patches-source = "anddea/revanced-patches"
arch = "arm64-v8a"
version = "auto"

[TikTok]
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
included-patches = "'SIM spoof'"
version = "auto"
arch = "arm64-v8a"
